web:
  extends:
    file: docker-compose-common.yml
    service: web
  links:
    - postgres
  environment:
    - S6_SERVICE_WHITELIST=mimir-prod-server cron
    - WORKER_ENV=production
postgres:
  image: postgres:9.4
  ports:
    - "5432:5432"
