web:
  extends:
    file: docker-compose-common.yml
    service: web
  volumes:
    - .:/code
  links:
    - postgres
  environment:
    - POSTGRES_TEST_HOST=postgres
    - S6_SERVICE_WHITELIST=webpack-dev-server mimir-dev-server cron
postgres:
  image: postgres:9.4
  ports:
    - "5432:5432"
