web:
  extends:
    file: docker-compose-common.yml
    service: web
  volumes:
    - .:/code
  links:
    - postgres
  environment:
    - S6_SERVICE_WHITELIST=webpack-dev-server mimir-dev-server cron
    - WORKER_ENV=development
  volumes_from:
    - data
postgres:
  image: postgres:9.4
  ports:
    - "5432:5432"
  volumes_from:
    - data
  environment:
    - PGDATA=/data/postgresql/pgdata
data:
  image: debian:jessie
  volumes:
    - /data/postgresql
    - /data/hashfs
  command: "true"
