"""remove old account tables

Revision ID: 44ff152e0a7c
Revises: c4a6c9b793c7
Create Date: 2021-03-11 22:20:38.225124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "44ff152e0a7c"
down_revision = "c4a6c9b793c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_entries")
    op.drop_table("authorized_users")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authorized_users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_authorized_users"),
        sa.UniqueConstraint("email", name="uq_authorized_users_email"),
    )
    op.create_table(
        "audit_entries",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["authorized_users.id"],
            name="fk_audit_entries_user_id_authorized_users",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_audit_entries"),
    )
    # ### end Alembic commands ###
