"""add changelog tables

Revision ID: c4a6c9b793c7
Revises: 4456da3ec475
Create Date: 2021-03-10 18:38:20.504468

"""
from alembic import op
import sqlalchemy as sa

from mimir import models


# revision identifiers, used by Alembic.
revision = "c4a6c9b793c7"
down_revision = "4456da3ec475"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_log_batches",
        sa.Column("id", models.column_types.Timeflake(), nullable=False),
        sa.Column("created_at", models.column_types.AwareDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_log_batches")),
    )
    op.create_table(
        "change_log_generic_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("detail", sa.UnicodeText(), nullable=False),
        sa.Column("created_at", models.column_types.AwareDateTime(), nullable=False),
        sa.Column("changelogbatch_id", models.column_types.Timeflake(), nullable=True),
        sa.ForeignKeyConstraint(
            ["changelogbatch_id"],
            ["change_log_batches.id"],
            name=op.f(
                "fk_change_log_generic_entries_changelogbatch_id_change_log_batches"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_log_generic_entries")),
    )
    op.create_table(
        "change_log_writeup_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("writeuppost_id", sa.Integer(), nullable=False),
        sa.Column("created_at", models.column_types.AwareDateTime(), nullable=False),
        sa.Column("changelogbatch_id", models.column_types.Timeflake(), nullable=True),
        sa.ForeignKeyConstraint(
            ["changelogbatch_id"],
            ["change_log_batches.id"],
            name=op.f(
                "fk_change_log_writeup_entries_changelogbatch_id_change_log_batches"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["writeuppost_id"],
            ["writeup_posts.id"],
            name=op.f("fk_change_log_writeup_entries_writeuppost_id_writeup_posts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_log_writeup_entries")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("change_log_writeup_entries")
    op.drop_table("change_log_generic_entries")
    op.drop_table("change_log_batches")
    # ### end Alembic commands ###
